Visitors.Web/Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Visitors.Domain;
using Visitors.Domain.Enums;
using Visitors.Models.PeopleViewModels;
using Visitors.Services;
using X.PagedList;

namespace Visitors.Web.Controllers
{
    public class PeopleController : Controller
    {
        private readonly PeopleService _peopleService;

        public PeopleController(PeopleService peopleService)
        {
            _peopleService = peopleService;
        }

        // GET: Visitors
        public async Task<IActionResult> Index(int page = 1)
        {
            page = page < 1
                ? 1
                : page;
            var query = await _peopleService
                .GetActiveAsync<PersonViewModel>();
            var pagedList = query
                .ToPagedList(page, Constants.ItemsPerPage);
            return View(pagedList);
        }

        // GET: Visitors/Details/5
        public async Task<IActionResult> Details(Guid id)
        {
            if (id == Guid.Empty)
            {
                return NotFound();
            }
            var person = await _peopleService.GetAsync(id, x => x.Visits);
            if (person == null)
            {
                return NotFound();
            }
            var detailPerson = Mapper.Map<PersonDetailViewModel>(person);
            return View(detailPerson);
        }

        // GET: Visitors/Create
        public IActionResult Create()
        {
            FillGenderList();
            return View();
        }

        // POST: Visitors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreatePersonViewModel model)
        {
            if (!ModelState.IsValid)
            {
                FillGenderList();
                return View(model);
            }
            try
            {
                model.Id = Guid.NewGuid();
                var person = Mapper.Map<Person>(model);
                Person firstPerson = await _peopleService.GetByIinAsync(model.IIN);
                if (firstPerson == null)
                {
                    await _peopleService.AddAsync(person);
                    await _peopleService.SaveAsync();
                    return RedirectToAction("Index");
                }
                else
                {
                    FillGenderList();
                    ModelState.AddModelError("Iin", "Посещаемый с таким ИИН уже существует");
                    return View(model);
                }
            }
            catch (Exception e)
            {
                FillGenderList();
                ModelState.AddModelError("", e.Message);
                return View(model);
            }
        }

        // GET: Visitors/Delete/5
        public async Task<IActionResult> Delete(Guid id)
        {
            var dbEntity = await _peopleService.GetAsync(id);
            if (dbEntity != null)
            {
                await _peopleService.DeleteAsync(dbEntity);
                await _peopleService.SaveAsync();
                return RedirectToAction("Index");
            }
            else
            {   //передать сообщение
                ViewData["Message"] = "Нет записи";
                ViewBag.Message = "Нет записи";
                return RedirectToAction("Index");
            }
        }

        private void FillGenderList()
        {
            Dictionary<string, string> selectDictionary = new Dictionary<string, string>();

            Type enumType = typeof(Gender);
            MemberInfo[] members = enumType.GetMembers();
            foreach (var memberInfo in members)
            {
                if (memberInfo.GetCustomAttribute(typeof(DisplayAttribute)) != null)
                {
                    selectDictionary.Add(memberInfo.Name,
                        ((DisplayAttribute)memberInfo.GetCustomAttribute(typeof(DisplayAttribute))).Name);
                }
            }

            ViewData.Add("GenderList", new SelectList(selectDictionary, "Key", "Value"));
        }
    }
}

Visitors.Web/Controllers/VisitsController.cs
using System;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Visitors.Domain;
using Visitors.Services;
using Visitors.Models.VisitsViewModels;
using X.PagedList;

namespace Visitors.Web.Controllers
{
    public class VisitsController : Controller
    {
        private readonly VisitorsService _visitorsService;
        private readonly PeopleService _peopleService;
        private readonly VisitsService _visitsService;


        public VisitsController(VisitorsService visitorService,
            PeopleService peopleService,
            VisitsService visitsService)
        {
            _visitorsService = visitorService;
            _peopleService = peopleService;
            _visitsService = visitsService;
        }

        // GET: Visitors
        public async Task<IActionResult> Index(int page = 1)
        {
            page = page < 1
                ? 1
                : page;
            var query = await _visitsService
                .GetActiveAsync<VisitViewModel>();
            var pagedList = query
                .ToPagedList(page, Constants.ItemsPerPage);
            return View(pagedList);
        }

        // GET: Visitors/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        // GET: Visitors/Create
        public async Task<IActionResult> Create()
        {
            await FillDropDownList();
            return View();
        }

        // POST: Visitors/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateVisitViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newVisit = Mapper.Map<Visit>(model);
                await _visitsService.AddAsync(newVisit);
                await _visitorsService.SaveAsync();
                return RedirectToAction("Index");
            }
            await FillDropDownList();
            return View(model);
        }

        // GET: Visitors/Delete/5
        public IActionResult Delete(Guid id)
        {
            return View();
        }

        private async  Task FillDropDownList()
        {
            var visitors = new SelectList( await _visitorsService.GetDropDownRecordsAsync(), "Value", "ValueText");
            ViewData.Add("VisitorsList", visitors);

            var people = new SelectList( await _peopleService.GetDropDownRecordsAsync(), "Value", "ValueText");
            ViewData.Add("PeopleList", people);
        }
    }
}

Visitors.Web/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Visitors.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Visitors.Web</a>

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" id="visitorsMenu" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Посетители<span class="caret"></span></a>

                        <ul class="dropdown-menu" aria-labelledby="visitorsMenu">
                            <li><a asp-controller="Visitors" asp-action="Create">Добавить</a></li>
                            <li><a asp-controller="Visitors" asp-action="Index">Список</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        @*<a href="#" class="dropdown-togglse" id="peopleMenu" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Посетители<span class="caret"></span></a>*@
                        <a href="#" class="dropdown-toggle" role="button" id="peopleMenu" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="true">Посещаемые<span class="caret"></span></a>
                        <ul class="dropdown-menu" aria-labelledby="peopleMenu">
                            <li><a asp-controller="People" asp-action="Create">Добавить</a></li>
                            <li><a asp-controller="People" asp-action="Index">Список</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" role="button" id="visitsMenu" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="true">
                            Посещения
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="visitsMenu">
                            <li><a asp-controller="Visits" asp-action="Create">Добавить</a></li>
                            <li><a asp-controller="Visits" asp-action="Index">Список</a></li>
                        </ul>
                    </li>
                </ul>
                @*@await Html.PartialAsync("_LoginPartial")*@
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Visitors.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>